title: Pawan R Poojary
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: false
theme: jekyll-theme-minimal


# Layout

show_frame: true           # adds a gray frame to the site

# menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "Awards" }
  - {title: "Publications" }
  - {title: "Teaching" }
  - {title: "Services" }
